/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SwcLceComManager_Type.h
 ********************************************************************/

#ifndef RTE_SWCLCECOMMANAGER_TYPE_H
#define RTE_SWCLCECOMMANAGER_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
    extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/


/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SWCLCECOMMANAGER_TYPE_H */
