/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SwcLceComManager_Interface.h
 ********************************************************************/

#ifndef RTE_SWCLCECOMMANAGER_INTERFACE_H_
#define RTE_SWCLCECOMMANAGER_INTERFACE_H_

#include "Rte_Type.h"
#include "Rte_SwcLceComManager.h"




class Rte_SwcLceComManager_Interface
{
public:

	virtual Std_ReturnType Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_DR (IComLight_Ctrl_Inputs_CTR_FN_DR_Type CTR_FN_DR) = 0;
	virtual Std_ReturnType Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_POS (IComLight_Ctrl_Inputs_CTR_FN_POS_Type CTR_FN_POS) = 0;
	virtual Std_ReturnType Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_PAR (IComLight_Ctrl_Inputs_CTR_FN_PAR_Type CTR_FN_PAR) = 0;
	virtual Std_ReturnType Rte_Read_SwcLceComManager_comLight_Ctrl_Inputs_ST_LP_LIN (IComLight_Ctrl_Inputs_ST_LP_LIN_Type* ST_LP_LIN) = 0;
	virtual Std_ReturnType Rte_Read_SwcLceComManager_comBrightness_Rain_Sensor_ST_RB_LIN (IComBrightness_Rain_Sensor_ST_RB_LIN_Type* ST_RB_LIN) = 0;
	virtual Std_ReturnType Rte_Read_SwcLceComManager_comCar_State_VEH_ST (IComCar_State_VEH_ST_Type* VEH_ST) = 0;
	virtual Std_ReturnType Rte_Read_SwcLceComManager_comMotor_Speed_Motor_Speed (IComMotor_Speed_Motor_Speed_Type* Motor_Speed) = 0;

};
#endif /* RTE_SWCLCECOMMANAGER_INTERFACE_H_ */
