/********************************************************************
 * Automatically generated by ARUnit
 * Filename: SwcLceComManager_FixtureBase.h
 ********************************************************************/

/*******************************************************************************************************
* Base test fixture class for added comfort while writing RTE level tests.
*******************************************************************************************************/

#ifndef SWCLCECOMMANAGER_FIXTUREBASE_H_
#define SWCLCECOMMANAGER_FIXTUREBASE_H_

#include "gtest/gtest.h"

#include "Rte_SwcLceComManager_Interface.h"
#include "Rte_SwcLceComManager_BufferDecorator.h"
#include "Rte_SwcLceComManager_Mock.h"
#include "Rte_SwcLceComManager_TraceDecorator.h"    


/** Performs basic RTE setup for tests.
*
* This includes optional rte buffer and trace. 
* Note that the trace isn't active until manually started.
*
*/
class SwcLceComManager_FixtureBase : public ::testing::Test
{
public:
    static const unsigned RTERUNNABLE_SWCLCECOMMANAGER_RUNCOMMNGR_10MSTASK_PERIOD_MS = 10u;
    ::testing::NiceMock <Rte_SwcLceComManager_Mock> _mock_SwcLceComManager;
    ::testing::NiceMock <Rte_SwcLceComManager_Mock>& _mock; // Shortcut without SWC name
    Rte_SwcLceComManager_BufferDecorator _rteBuffer_SwcLceComManager;
    Rte_SwcLceComManager_BufferDecorator& _rteBuffer; // Shortcut without SWC name
    Rte_SwcLceComManager_TraceDecorator _rteTrace_SwcLceComManager;
    Rte_SwcLceComManager_TraceDecorator& _rteTrace; // Shortcut without SWC name
    
    SwcLceComManager_FixtureBase();
    
    
    /// Runs for given milliseconds. Will call cyclic runnables if they are scheduling in that time slot.
    virtual void run(unsigned ms);
    
    /// Will clear all test setup (expectations and on_calls) and re-initialize
    virtual void reinitialize() {
        reinitializeWithDefaultValues();
    }

    virtual void reinitializeWithZeroes();
    virtual void reinitializeWithDefaultValues();
    
    //Define server call points
    
    virtual void setTime(unsigned ms);
    
    virtual unsigned getTime() { return _currentTime; }
    
    /* initializes with 0 */
    virtual void initializeWithZeroes();
    
    /* initializes with specified init values or another possible value. Other possible value can be enumeration value or 0. */
    virtual void initializeWithDefaultValues();
    
protected:
    unsigned _currentTime;
    unsigned _RTERunnable_SwcLceComManager_RunComMngr_10msTask_LastRunTime;
    bool _RTERunnable_SwcLceComManager_RunComMngr_10msTask_WasExecuted;            
    
    virtual ~SwcLceComManager_FixtureBase();
    virtual void SetUp();
    virtual void TearDown();
};
#endif /* SWCLCECOMMANAGER_FixtureBase_H_*/
