/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SwcLceComManager_BufferDecorator.h
 ********************************************************************/

#ifndef RTE_SWCLCECOMMANAGER_BUFFERDECORATOR_H_
#define RTE_SWCLCECOMMANAGER_BUFFERDECORATOR_H_

#include <algorithm>
#include "Rte_Type.h"
#include "Rte_SwcLceComManager_Interface.h"

//Buffer class for RTE.


class Rte_SwcLceComManager_BufferDecorator : public Rte_SwcLceComManager_Interface
{
public:
	Rte_SwcLceComManager_BufferDecorator (Rte_SwcLceComManager_Interface* component);
	
	 IComLight_Ctrl_Inputs_CTR_FN_DR_Type get_Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_DR_Buf() const;
	 IComLight_Ctrl_Inputs_CTR_FN_POS_Type get_Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_POS_Buf() const;
	 IComLight_Ctrl_Inputs_CTR_FN_PAR_Type get_Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_PAR_Buf() const;
	 IComLight_Ctrl_Inputs_ST_LP_LIN_Type get_Rte_Read_SwcLceComManager_comLight_Ctrl_Inputs_ST_LP_LIN_Buf() const;
	 IComBrightness_Rain_Sensor_ST_RB_LIN_Type get_Rte_Read_SwcLceComManager_comBrightness_Rain_Sensor_ST_RB_LIN_Buf() const;
	 IComCar_State_VEH_ST_Type get_Rte_Read_SwcLceComManager_comCar_State_VEH_ST_Buf() const;
	 IComMotor_Speed_Motor_Speed_Type get_Rte_Read_SwcLceComManager_comMotor_Speed_Motor_Speed_Buf() const;
	Std_ReturnType get_Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_DR_ReturnValue() const;
	Std_ReturnType get_Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_POS_ReturnValue() const;
	Std_ReturnType get_Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_PAR_ReturnValue() const;
	Std_ReturnType get_Rte_Read_SwcLceComManager_comLight_Ctrl_Inputs_ST_LP_LIN_ReturnValue() const;
	Std_ReturnType get_Rte_Read_SwcLceComManager_comBrightness_Rain_Sensor_ST_RB_LIN_ReturnValue() const;
	Std_ReturnType get_Rte_Read_SwcLceComManager_comCar_State_VEH_ST_ReturnValue() const;
	Std_ReturnType get_Rte_Read_SwcLceComManager_comMotor_Speed_Motor_Speed_ReturnValue() const;
			
/////////////////////////////////////////
// Overwritten mock functions. Delegates and writes buffer values.

	virtual Std_ReturnType Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_DR (IComLight_Ctrl_Inputs_CTR_FN_DR_Type CTR_FN_DR);
	virtual Std_ReturnType Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_POS (IComLight_Ctrl_Inputs_CTR_FN_POS_Type CTR_FN_POS);
	virtual Std_ReturnType Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_PAR (IComLight_Ctrl_Inputs_CTR_FN_PAR_Type CTR_FN_PAR);
	virtual Std_ReturnType Rte_Read_SwcLceComManager_comLight_Ctrl_Inputs_ST_LP_LIN (IComLight_Ctrl_Inputs_ST_LP_LIN_Type* ST_LP_LIN);
	virtual Std_ReturnType Rte_Read_SwcLceComManager_comBrightness_Rain_Sensor_ST_RB_LIN (IComBrightness_Rain_Sensor_ST_RB_LIN_Type* ST_RB_LIN);
	virtual Std_ReturnType Rte_Read_SwcLceComManager_comCar_State_VEH_ST (IComCar_State_VEH_ST_Type* VEH_ST);
	virtual Std_ReturnType Rte_Read_SwcLceComManager_comMotor_Speed_Motor_Speed (IComMotor_Speed_Motor_Speed_Type* Motor_Speed);
	
	private:
		Rte_SwcLceComManager_Interface* _component; //component to decorate

	IComLight_Ctrl_Inputs_CTR_FN_DR_Type _Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_DR_Buf;
	IComLight_Ctrl_Inputs_CTR_FN_POS_Type _Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_POS_Buf;
	IComLight_Ctrl_Inputs_CTR_FN_PAR_Type _Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_PAR_Buf;
	IComLight_Ctrl_Inputs_ST_LP_LIN_Type _Rte_Read_SwcLceComManager_comLight_Ctrl_Inputs_ST_LP_LIN_Buf;
	IComBrightness_Rain_Sensor_ST_RB_LIN_Type _Rte_Read_SwcLceComManager_comBrightness_Rain_Sensor_ST_RB_LIN_Buf;
	IComCar_State_VEH_ST_Type _Rte_Read_SwcLceComManager_comCar_State_VEH_ST_Buf;
	IComMotor_Speed_Motor_Speed_Type _Rte_Read_SwcLceComManager_comMotor_Speed_Motor_Speed_Buf;

	Std_ReturnType _Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_DR_ReturnValue;
	Std_ReturnType _Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_POS_ReturnValue;
	Std_ReturnType _Rte_Write_SwcLceComManager_comCTR_EL_F_CTR_FN_PAR_ReturnValue;
	Std_ReturnType _Rte_Read_SwcLceComManager_comLight_Ctrl_Inputs_ST_LP_LIN_ReturnValue;
	Std_ReturnType _Rte_Read_SwcLceComManager_comBrightness_Rain_Sensor_ST_RB_LIN_ReturnValue;
	Std_ReturnType _Rte_Read_SwcLceComManager_comCar_State_VEH_ST_ReturnValue;
	Std_ReturnType _Rte_Read_SwcLceComManager_comMotor_Speed_Motor_Speed_ReturnValue;
};
#endif /* RTE_SwcLceComManager_BUFFERDECORATOR_H_ */
